name: InPIDS
version: 0.4.4
main: me.fiveave.inpids.main
api-version: '1.19'
description: PIDS Plugin
author: 5_AvenueLocal
depend: [ Train_Carts ]
commands:
  inpids:
    description: InPIDS Main Commands
    usage: /inpids